steps:

- name: gcr.io/cloud-builders/docker
  args:
  - pull
  - gcr.io/$_STAGING_PROJECT_ID/testrunner:sha_$COMMIT_SHA

- name: gcr.io/cloud-builders/docker
  args:
  - tag
  - gcr.io/$_STAGING_PROJECT_ID/testrunner:sha_$COMMIT_SHA
  - gcr.io/$PROJECT_ID/testrunner:$TAG_NAME

- name: gcr.io/cloud-builders/gcloud
  entrypoint: /workspace/cloudbuild/tag_latest.sh
  args:
  - gcr.io/$PROJECT_ID/testrunner
  - "$TAG_NAME"

images:
- gcr.io/$PROJECT_ID/testrunner:$TAG_NAME
- gcr.io/$PROJECT_ID/testrunner:latest
